### ISSUE TITLE
An ERROR show in compiling a DLL project

### ISSUE THREAD

**Issue by AthonyLi** [VladRoma/gpsvp#159]
I will Create a dll project;when I conpiling this project ,have an error produce:
`Description	Resource	Path	Location	Type
./src/value/ArrayNamedValue.o: relocation R_X86_64_32S against "_ZTVN4IOTP15ArrayNamedValueE"can not be used when making a shared object; recompile with -fPIC	DLL_CPPCommon		 	C/C++ Problem`
can you help me? 
@dothebart   @jsteemann

**Comment by jsteemann** [comment]
@AthonyLi : can't help here. But from the error message it looks like you need to compile with `-fPIC` option to create position-independent code (as it's an .so or a .dll).
