### ISSUE TITLE
A Question about ArangoDB3.0

### ISSUE THREAD

**Issue by AthonyLi** [VladRoma/gpsvp#160]
A month ago,I use ArangoDB 2.8 to test stability, I write a program to insert record to database; every second insert three record and it sustain 7 days,an then it's broken, but it work at linux very well,so I decide to develop in linux; However,in linux,we encounted many troubles,and you give me help too much.Thank you very much; At last , I wonder ask you what the ArangoDB 3.0's performance  on windows ?

@dothebart @jsteemann

**Comment by dothebart** [comment]
The windows instabilities with the V8 garbage collection should be gone with the new V8 version in 3.0. In general, if you want the most computing power out of your hardware, its not windows what you would choose, regardless of the application / server stack you run. For reference, search the windows systems in: https://www.top500.org/ (and these guys really care to get the most out of their hardware)

**Comment by AthonyLi** [comment]
hm,you mean that the ` ArangoDB 3.0` 's stabilities was good in windows ? in other words, it will crash down frequently like 2.8 ?
